---
title: "Presidents"
author: "Malaika Handa"
date: "September 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the library
```{r, warning = FALSE, message = FALSE}
library(tidyverse)
```

## Load the data
```{r, warning = FALSE, message = FALSE}
all = read_csv("presidents.csv")
names(all)
```

## Add a column
```{r}
full_names = all$president
all$last_name = sapply(strsplit(full_names, split = " "),
                        function(x) x[length(x)])
all$last_name
```

## Reduce the data
```{r}
affiliations = all[which(all$affiliation != "None"), ]
post_1950 = all[which(all$inauguration_year > 1950), ]
parties = all[which(!(all$party %in% c("Non-partisan",
                                       "National Union",
                                       "Federalist"))), ] # only one value for each of these parties
```

## Create a labeller
```{r}
affiliation_labeller = function(variable, value) {
  affiliation_names = list("P" = "Progressive",
                           "C" = "Conservative")
  label = affiliation_names[value]
  return(label)
}
```

## Create a plot using the two affiliations
```{r, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 15}
affiliations_plot =
  ggplot(affiliations,
         aes(x = inauguration_year,
             y = age)) +
    geom_point(aes(color = affiliation),
               size = 4.5) +
    scale_colour_manual(values = c("C" = "red",
                                   "P" = "blue",
                                   "None" = "black")) +
    geom_text(aes(label = last_name),
              hjust = -0.2,
              vjust = 0.3,
              size = 3) +
    coord_cartesian(xlim = c(1770, 2030)) + 
    facet_wrap(~ affiliation,
               labeller = affiliation_labeller) +
    labs(title = "Age of presidents at inauguration, by affiliation",
         x = "Inauguration Year",
         y = "Age, in years") +
    theme(legend.position = "none")
```

## Save without the trend lines
```{r, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 15}
affiliations_plot
ggsave("affiliations.jpg")
```

## And with lines
```{r, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 15}
affiliations_plot + geom_smooth(color = "black",
                        method = "lm",
                        level = 0)
ggsave("affiliations_lines.jpg")
```

## Create a plot using the actual parties
```{r, warning = FALSE, message = FALSE, fig.height = 12, fig.width = 15}
party_plot =
  ggplot(parties,
         aes(x = inauguration_year,
             y = age)) +
    geom_point(aes(color = party),
               size = 4.5) +
    geom_text(aes(label = last_name),
              hjust = -0.3,
              vjust = 0.3,
              size = 3) +
    coord_cartesian(xlim = c(1770, 2030)) + 
    facet_wrap(~ party,
               nrow = 2) +
    labs(title = "Age of presidents at inauguration, by party",
         x = "Inauguration Year",
         y = "Age, in years") +
   theme(legend.position = "none")

party_plot
ggsave("parties.jpg")
```

## Create a plot using only data after 1950
```{r, warning = FALSE, message = FALSE, fig.height = 8, fig.width = 15}
post_1950_plot =
  ggplot(post_1950,
         aes(x = inauguration_year,
             y = age)) +
    geom_point(aes(color = party),
               size = 6) +
    geom_text(aes(label = last_name),
              hjust = -0.35,
              vjust = 0.3,
              size = 5) +
    coord_cartesian(xlim = c(1940, 2030)) +
    scale_colour_manual(values = c("Republican" = "red",
                                   "Democrat" = "blue")) +
    facet_wrap(~ party,
               ncol = 2) +
    labs(title = "Age of presidents at inauguration, by party (post-1950)",
         x = "Inauguration Year",
         y = "Age, in years") +
   theme(legend.position = "none")

post_1950_plot
ggsave("post_1950.jpg")
```

## Contact me

* [Twitter](https://twitter.com/malicodes)
* [LinkedIn](https://www.linkedin.com/in/malaika-handa/)
* [Resume](https://drive.google.com/file/d/1ammnktVHH-GdZ2UOsGCsUS_VM3w8csh8/view?usp=sharing)


